[package]
name = "onboard-next"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
onboard-core = { path = "../onboard-core" }
onboard-bridge-api = { path = "../onboard-bridge-api" }
onboard-bridge-windows = { path = "../onboard-bridge-windows" }
onboard-bridge-macos = { path = "../onboard-bridge-macos" }

[target.'cfg(any(windows, target_os = "macos"))'.dependencies]
eframe = { version = "=0.27.2", default-features = false, features = ["default_fonts", "glow", "persistence"] }

[target.'cfg(windows)'.dependencies]
raw-window-handle = "=0.6.2"
serde = { version = "=1.0.210", features = ["derive"] }
serde_json = "=1.0.128"
tray-icon = "=0.21.3"
ureq = { version = "=2.12.1", default-features = false, features = ["tls"] }

[lints]
workspace = true
